version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    target-branch: main
    open-pull-requests-limit: 10
    labels:
      - dependencies
    groups:
      nestjs-core:
        patterns:
          - '@nestjs/*'
      tooling:
        patterns:
          - '@typescript-eslint/*'
          - eslint*
          - prettier
          - turbo
          - typescript

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: main
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
